# Generated by Django 4.1.7 on 2023-04-01 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_passwordreset'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordReset',
        ),
    ]
