# Generated by Django 4.1.7 on 2023-04-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_customer_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
