# Generated by Django 4.1.7 on 2023-04-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0006_alter_customer_is_subscribed_to_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='is_subscribed_to_newsletter',
            field=models.BooleanField(default=False),
        ),
    ]
