# Generated by Django 4.1.7 on 2023-04-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0007_alter_customer_is_subscribed_to_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='old_password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
