# Generated by Django 4.1.7 on 2023-04-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0009_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='address',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='passport_no',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='subscription',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
