# Generated by Django 4.1.7 on 2023-04-14 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0010_remove_subscription_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
